language: go

go: 1.5.1

dist: trusty

group: edge

services:
- rabbitmq
- docker

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'

addons:
  artifacts:
    paths:
    - './build/$UNAME/amd64/travis-worker'
    target_paths:
    - 'travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER'
    - 'travis-ci/worker/$(git describe --always --dirty --tags)'
    - 'travis-ci/worker/$TRAVIS_BRANCH'

install:
- go get github.com/FiloSottile/gvt
- go get github.com/alecthomas/gometalinter
- gometalinter --install --update
- gem install package_cloud --no-ri --no-rdoc

script:
- make deps
- make lintall
- make test
- make test-race
- make smoke
- make package
- make smoke-package

after_success:
- utils/atlas-push
- mkdir -p build/$UNAME/amd64
- cp -v $TRAVIS_BUILD_DIR/bin/travis-worker ./build/$UNAME/amd64/travis-worker
- echo $ARTIFACTS_PATHS

notifications:
  slack:
    rooms:
    - secure: "EeyaCTxwBPk17BC55brkWSQ9d8EEhKgJ9KHTIJzJnfGasXeUZWRzV80fT/eXcvWXnpq1GkP01xk1V60EC0G9XxLlHfCXbSJAAAr4vb0vadIB9LmVrWfOr1J2aRh4g5Vtk5zWBp2Qv4DVo8KdOVKR2MHI+bjtLFwZVvYmQSt+tzo="
