language: go
go: 1.10.x
sudo: required
dist: trusty
group: edge

cache:
  directories:
    - vendor

services:
- rabbitmq
- docker
- redis

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"

jobs:
  include:
    - stage: test
      name: "linux"
      script:
        - travis_retry make deps
        - make lintall
        - make build
        - make test
        - make smoke
        - mkdir -p build/linux/amd64
        - cp $GOPATH/bin/travis-worker build/linux/amd64
      addons:
        artifacts:
          paths:
            - ./build/linux/amd64/travis-worker
          target_paths:
            - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
            - travis-ci/worker/$(git describe --always --dirty --tags)
            - travis-ci/worker/$TRAVIS_BRANCH
    - name: "macos"
      os: osx
      script:
        - travis_retry make deps
        - make lintall
        - make build
        - make test
        - make smoke
        - mkdir -p build/darwin/amd64
        - cp $GOPATH/bin/travis-worker build/darwin/amd64
      addons:
        artifacts:
          paths:
            - ./build/darwin/amd64/travis-worker
          target_paths:
            - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
            - travis-ci/worker/$(git describe --always --dirty --tags)
            - travis-ci/worker/$TRAVIS_BRANCH
    - name: "docker"
      if: type != 'pull_request' && env(DOCKER_LOGIN_PASSWORD) is present && env(DOCKER_LOGIN_USERNAME) is present
      script:
        - make docker-build
        - make smoke-docker
        - make docker-push
        - make send-docker-hub-trigger
      addons:
        apt:
          update: true
          packages:
            - docker-ce
    - name: "http-job-test"
      script:
        - travis_retry make deps
        - make build
        - mkdir -p build/linux/amd64
        - cp $GOPATH/bin/travis-worker build/linux/amd64
        - make http-job-test
