language: go

go: 1.5.1

dist: trusty

group: edge

services:
- rabbitmq
- docker

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - UNAME="$(uname | tr '[:upper:]' '[:lower:]')"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'

addons:
  artifacts:
    paths:
    - "./build/$UNAME/amd64/travis-worker"
    target_paths:
    - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    - travis-ci/worker/$(git describe --always --dirty --tags)
    - travis-ci/worker/$TRAVIS_BRANCH

install:
- go get github.com/FiloSottile/gvt
- go get github.com/alecthomas/gometalinter
- go get github.com/laher/goxc
- gometalinter --install --update
- gem install package_cloud --no-ri --no-rdoc

script:
- make deps
- make lintall
- make test
- make test-race
- make crossbuild
- make smoke
- make package
- make smoke-package

after_success:
- utils/atlas-push
- echo $ARTIFACTS_PATHS

notifications:
  slack:
    secure: IyWrJhruYYHEIvi4YsN3vV2rycctnRiIolzUMwgiDo275AK6O4h58+fu1EXFjMZmCqdOan98MsF709yW3S9zDaZo2s233dKWzQ95S8+n2RS+pGsxBZacCiEvOh0u1K3f19hpf8zj0ybtpcox+a6yrxK+F3er9WveO39yPZjzwCA=
