language: go
go: 1.10.x
sudo: required
dist: trusty
group: edge

cache:
  directories:
    - vendor

services:
- rabbitmq
- docker
- redis

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"

jobs:
  include:
    - stage: test
      name: "build and ship"
      script:
        - travis_retry make deps
        - make lintall
        - make test
        - make crossbuild
        - make smoke
        - if [[ $TRAVIS_PULL_REQUEST = 'false' && $DOCKER_LOGIN_PASSWORD && $DOCKER_LOGIN_USERNAME ]]; then
            sudo apt-get update;
            sudo apt-get -y install docker-ce;
            make docker-build smoke-docker docker-push;
          fi
        - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
        - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
        - make send-docker-hub-trigger
      addons:
        artifacts:
          paths:
            - ./build/linux/amd64/travis-worker
            - ./build/darwin/amd64/travis-worker
          target_paths:
            - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
            - travis-ci/worker/$(git describe --always --dirty --tags)
            - travis-ci/worker/$TRAVIS_BRANCH
    - name: "http-job-test"
      script:
        - travis_retry make deps
        - make build
        - mkdir -p build/linux/amd64
        - cp $GOPATH/build/linux/amd64/travis-worker build/linux/amd64
        - make http-job-test
