# my global config
global:
  scrape_interval:     1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    static_configs:
    - targets: ['localhost:9091']
    honor_labels: true
